version: 0.2

phases:
  install:
    commands:
      - 'rm -f /codebuild/global.json || true'
      - wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
      - chmod +x /tmp/dotnet-install.sh
      - /tmp/dotnet-install.sh --channel 9.0 --install-dir /usr/local/dotnet
      - /tmp/dotnet-install.sh --channel 9.0 --install-dir /usr/local/dotnet --runtime aspnetcore
      - export PATH="/usr/local/dotnet:$PATH"
      - export DOTNET_ROOT="/usr/local/dotnet"
      - dotnet --version

  build:
    commands:
      - export PATH="/usr/local/dotnet:$PATH"
      - dotnet --version
      - dotnet restore SpendWiseApi.sln
      - dotnet build SpendWiseApi.sln -c Release --no-restore
      - dotnet publish SpendWiseApi/SpendWiseApi.csproj -c Release -o publish /p:SelfContained=false /p:GenerateRuntimeConfigurationFiles=true /p:RuntimeIdentifier=linux-x64
      - echo "Checking publish output..."
      - ls -la publish/
      - echo "Checking for runtimeconfig.json files..."
      - 'ls -la publish/*.runtimeconfig.json || echo "No runtimeconfig.json found, creating one..."'
      - |
        if [ ! -f publish/SpendWiseApi.runtimeconfig.json ]; then
          echo "Creating SpendWiseApi.runtimeconfig.json..."
          echo '{"runtimeOptions":{"tfm":"net9.0","framework":{"name":"Microsoft.AspNetCore.App","version":"9.0.0"},"configProperties":{"System.GC.Server":true,"System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization":false}}}' > publish/SpendWiseApi.runtimeconfig.json
        fi
      - echo "Verifying runtimeconfig.json exists..."
      - ls -la publish/SpendWiseApi.runtimeconfig.json
      - cat publish/SpendWiseApi.runtimeconfig.json
      - cd publish
      - echo "Creating deployment package..."
      - zip -r ../app-deploy.zip .
      - cd ..
      - echo "Verifying runtimeconfig.json is in zip..."
      - 'unzip -l app-deploy.zip | grep runtimeconfig.json || echo "WARNING: runtimeconfig.json not found in zip"'

artifacts:
  files:
    - app-deploy.zip
  name: SpendWiseApi-$(date +%Y-%m-%d)
