version: 0.2

phases:
  install:
    commands:
      - rm -f /codebuild/global.json || true
      - wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
      - chmod +x /tmp/dotnet-install.sh
      - /tmp/dotnet-install.sh --channel 9.0 --install-dir /usr/local/dotnet
      - /tmp/dotnet-install.sh --channel 9.0 --install-dir /usr/local/dotnet --runtime aspnetcore
      - export PATH="/usr/local/dotnet:$PATH"
      - export DOTNET_ROOT="/usr/local/dotnet"
      - dotnet --version

  build:
    commands:
      - export PATH="/usr/local/dotnet:$PATH"
      - dotnet --version
      - dotnet restore SpendWiseApi.sln
      - dotnet build SpendWiseApi.sln -c Release --no-restore
      - dotnet publish SpendWiseApi/SpendWiseApi.csproj -c Release -o publish /p:SelfContained=false /p:GenerateRuntimeConfigurationFiles=true
      - |
        if [ ! -f publish/SpendWiseApi.runtimeconfig.json ]; then
          echo '{"runtimeOptions":{"tfm":"net9.0","framework":{"name":"Microsoft.AspNetCore.App","version":"9.0.0"},"configProperties":{"System.GC.Server":true}}}' > publish/SpendWiseApi.runtimeconfig.json
        fi
      - cd publish
      - zip -r ../app-deploy.zip .
      - cd ..

artifacts:
  files:
    - app-deploy.zip
  name: SpendWiseApi-$(date +%Y-%m-%d)
