version: "0.2"

phases:
  install:
    commands:
      - echo "Installing .NET 9 SDK..."
      - curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --channel 9.0
      - export DOTNET_ROOT=$HOME/.dotnet
      - export PATH=$HOME/.dotnet:$PATH
      - dotnet --version

  pre_build:
    commands:
      - echo "AWS CLI version:"
      - aws --version
      - echo "Working directory:"
      - pwd
      - ls -la

  build:
    commands:
      - echo "Restoring packages..."
      - dotnet restore SpendWiseApi.sln

      - echo "Building solution..."
      - dotnet build SpendWiseApi.sln -c Release --no-restore

      - echo "Publishing application..."
      - dotnet publish SpendWiseApi/SpendWiseApi.csproj \
          -c Release \
          -o publish \
          --no-build

      - echo "Verifying publish output..."
      - ls -la publish
      - test -f publish/SpendWiseApi.dll || exit 1

      - echo "Checking runtimeconfig.json..."
      - ls publish/*.runtimeconfig.json

      - echo "Creating deployment ZIP..."
      - cd publish
      - zip -r ../app-deploy.zip .
      - cd ..

artifacts:
  files:
    - app-deploy.zip
  name: SpendWiseApi-$(date +%Y-%m-%d)
