version: 0.2

phases:
  install:
    commands:
      # Commands to install .NET 9 SDK using Microsoft's install script
      - curl -L https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 9.0.100
      # Add the newly installed dotnet directory to the PATH
      - export PATH=$PATH:$HOME/.dotnet
      - dotnet --version
  pre_build:
    commands:
      - echo Restoring NuGet packages
      - dotnet restore SpendWiseApi.sln
  build:
    commands:
      # Use the dotnet CLI to build your project
      - dotnet build SpendWiseApi.sln -c Release
      - echo Publishing application
      - dotnet publish SpendWiseApi/SpendWiseApi.csproj -c Release -o publish
      - echo Verifying publish output
      - ls -la publish
      - cd publish
      - zip -r ../app-deploy.zip .
      - cd ..
      - echo Deployment package created
      - ls -lh app-deploy.zip

artifacts:
  files:
    - app-deploy.zip
  name: SpendWiseApi-$(date +%Y-%m-%d)
