version: 0.2

phases:
  install:
    commands:
      - rm -f /codebuild/global.json || true
      - wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
      - chmod +x /tmp/dotnet-install.sh
      - /tmp/dotnet-install.sh --channel 8.0 --install-dir /usr/local/dotnet
      - export DOTNET_ROOT=/usr/local/dotnet
      - export PATH=$DOTNET_ROOT:$PATH
      - dotnet --version

  build:
    commands:
      - dotnet restore SpendWiseApi.sln
      - dotnet publish SpendWiseApi/SpendWiseApi.csproj -c Release -o publish
      - echo "Publish output:"
      - ls -la publish
      - echo "Verifying runtimeconfig.json:"
      - ls publish/*.runtimeconfig.json
      - cd publish
      - zip -r ../app-deploy.zip .
      - cd ..

artifacts:
  files:
    - app-deploy.zip
  name: SpendWiseApi-$(date +%Y-%m-%d)
