version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - rm -f global.json || true
      - dotnet --version

  build:
    commands:
      - ls -la
      - dotnet restore SpendWiseApi.sln --source https://api.nuget.org/v3/index.json
      - dotnet publish SpendWiseAPI/SpendWiseApi.csproj -c Release -o publish
      - ls -la publish
      - cd publish
      - zip -r ../app-deploy.zip .
      - cd ..

artifacts:
  files:
    - app-deploy.zip
  name: SpendWiseApi-$(date +%Y-%m-%d)
