version: "0.2"

phases:
  install:
    commands:
      - echo "Installing .NET 9 SDK..."
      - curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --channel 9.0 --install-dir /root/.dotnet
      - export DOTNET_ROOT=/root/.dotnet
      - export PATH=/root/.dotnet:$PATH
      - echo "SDKs installed:"
      - dotnet --list-sdks

  build:
    commands:
      - echo "Restoring solution..."
      - dotnet restore SpendWiseApi.sln
      - echo "Publishing solution..."
      - dotnet publish SpendWiseApi.sln -c Release -o publish

artifacts:
  files:
    - publish/**/*
