version: "0.2"

phases:
  install:
    commands:
      - echo "Installing .NET 9 SDK..."
      - curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --version 9.0.308 --install-dir /usr/local/share/dotnet
      - export DOTNET_ROOT=/usr/local/share/dotnet
      - export PATH=/usr/local/share/dotnet:$PATH
      - echo "Installed SDKs:"
      - dotnet --list-sdks
      - dotnet --version

  build:
    commands:
      - echo "Restoring solution..."
      - dotnet restore SpendWiseApi.sln
      - echo "Publishing solution..."
      - dotnet publish SpendWiseApi.sln -c Release -o publish
      - echo "Zipping published output..."
      - zip -r app.zip publish

artifacts:
  files:
    - 'app.zip'
